import yfinance as yf
from datetime import datetime
import os
import pandas as pd

# Define the list of symbols
symbols = [ "A", "AA", "AAAU", "AAL", "AAN", "AAOI", "AAON", "AAP",
"AAPL", "AAT", "AAWW", "AAXJ", "AB", "ABBV", "ABC", "ABCB", "ABCL",
"ABCM", "ABEO", "ABG", "ABM", "ABMD", "ABNB", "ABOS", "ABR", "ABSI",
"ABST", "ABT", "ABTX", "ABUS", "AC", "ACA", "ACAD", "ACB", "ACC", "ACCD",
"ACCO", "ACEL", "ACES", "ACET", "ACGL", "ACHC", "ACHL", "ACHR", "ACI",
"ACIU", "ACIW", "ACLS", "ACLX", "ACM", "ACMR", "ACN", "ACNB", "ACQR",
"ACRE", "ACRS", "ACRX", "ACT", "ACTG", "ACV", "ACVA", "ACWI", "ACWX",
"ACXP", "ADAG", "ADBE", "ADC", "ADEA", "ADES", "ADGI", "ADI", "ADM",
"ADMA", "ADNT", "ADP", "ADPT", "ADRE", "ADS", "ADSK", "ADT", "ADTN",
"ADTX", "ADUS", "ADV", "ADVM", "AE", "AEE", "AEG", "AEIS", "AEL", "AEM",
"AEO", "AEP", "AER", "AERI", "AES", "AEVA", "AFCG", "AFG", "AFIB",
"AFL", "AFMD", "AFRM", "AFYA", "AG", "AGCB", "AGCO", "AGEN", "AGFS",
"AGFY", "AGG", "AGGY", "AGI", "AGIO", "AGL", "AGLE", "AGM", "AGNC",
"AGO", "AGQ", "AGR", "AGRI", "AGRO", "AGRX", "AGS", "AGTC", "AGTI",
"AGX", "AGYS", "AHCO", "AHH", "AI", "AIA", "AIG", "AIMC", "AIN", "AINV",
"AIQ", "AIR", "AIRC", "AIRR", "AIT", "AIV", "AIZ", "AJG", "AJRD", "AJX",
"AKAM", "AKBA", "AKR", "AKRO", "AKTS", "AKUS", "AKYA", "AL", "ALB",
"ALBO", "ALC", "ALCO", "ALDX", "ALE", "ALEC", "ALEX", "ALF", "ALG",
"ALGM", "ALGN", "ALGS", "ALGT", "ALHC", "ALIT", "ALK", "ALKS", "ALKT",
"ALL", "ALLE", "ALLK", "ALLO", "ALLY", "ALNY", "ALRM", "ALRS", "ALSN",
"ALTG", "ALTO", "ALTR", "ALTS", "ALV", "ALVR", "ALX", "ALXO", "ALZN",
"AM", "AMAL", "AMAM", "AMAT", "AMBA", "AMBC", "AMBP", "AMC", "AMCR",
"AMCX", "AMD", "AME", "AMED", "AMEH", "AMG", "AMGN", "AMH", "AMJ", "AMK",
"AMKR", "AMLP", "AMLX", "AMN", "AMNB", "AMOT", "AMP", "AMPH", "AMPL",
"AMPS", "AMPY", "AMR", "AMRC", "AMRK", "AMRN", "AMRS", "AMRX", "AMSC",
"AMSF", "AMST", "AMSWA", "AMT", "AMTB", "AMTI", "AMWD", "AMWL", "AMZN",
"AN", "ANAB", "ANAT", "ANDE", "ANEB", "ANET", "ANF", "ANGI", "ANGL",
"ANGN", "ANGO", "ANIK", "ANIP", "ANNX", "ANPC", "ANSS", "ANTM", "ANVS",
"ANY", "AOA", "AOK", "AOM", "AOMR", "AON", "AOR", "AORT", "AOS", "AOSL",
"AOUT", "APA", "APAM", "APD", "APEI", "APG", "APH", "API", "APLD", "APLE",
"APLS", "APLT", "APO", "APOG", "APP", "APPF", "APPH", "APPN", "APPS",
"APR", "APRE", "APT", "APTS", "APTV", "APTX", "APVO", "APYX", "AQB",
"AQN", "AQST", "AQUA", "AR", "ARAV", "ARAY", "ARB", "ARCB", "ARCC",
"ARCE", "ARCH", "ARCO", "ARCT", "ARDX", "ARE", "ARES", "ARGO", "ARGT",
"ARGX", "ARHS", "ARI", "ARIS", "ARKF", "ARKG", "ARKK", "ARKO", "ARKQ",
"ARKW", "ARL", "ARLO", "ARLP", "ARMK", "ARMR", "ARNA", "ARNC", "AROC",
"AROW", "ARQT", "ARR", "ARRY", "ARTNA", "ARVL", "ARVN", "ARW", "ARWR",
"ASAN", "ASB", "ASC", "ASGN", "ASH", "ASHR", "ASHX", "ASIX", "ASLE",
"ASMB", "ASML", "ASO", "ASPN", "ASPS", "ASPU", "ASTE", "ASTL", "ASTR",
"ASTS", "ASUR", "ASX", "ATAI", "ATC", "ATCO", "ATEC", "ATEN", "ATEX",
"ATGE", "ATHA", "ATHM", "ATHX", "ATI", "ATIP", "ATKR", "ATLC", "ATLO",
"ATNI", "ATNX", "ATO", "ATOM", "ATOS", "ATR", "ATRA", "ATRC", "ATRI",
"ATRO", "ATRS", "ATSG", "ATUS", "ATVI", "ATXI", "ATY", "AU", "AUB",
"AUBN", "AUDC", "AUPH", "AUR", "AURA", "AUUD", "AUVI", "AUY", "AVA",
"AVAH", "AVAL", "AVAV", "AVB", "AVCO", "AVD", "AVDX", "AVEM", "AVEO",
"AVGO", "AVID", "AVIR", "AVLR", "AVNS", "AVNT", "AVO", "AVPT", "AVRO",
"AVT", "AVTA", "AVTE", "AVTR", "AVUV", "AVXL", "AVY", "AVYA", "AWAY",
"AWH", "AWI", "AWK", "AWR", "AX", "AXDX", "AXGN", "AXL", "AXLA", "AXNX",
"AXON", "AXP", "AXS", "AXSM", "AXTA", "AXTI", "AY", "AYI", "AYLA",
"AYTU", "AYX", "AZEK", "AZO", "AZPN", "AZRE", "AZTA", "AZYO", "AZZ",
"B", "BA", "BAB", "BAC", "BAH", "BALL", "BALY", "BAM", "BAMR", "BANC",
"BAND", "BANF", "BANR", "BAOS", "BAP", "BAPR", "BAR", "BARK", "BASE",
"BATRA", "BATRK", "BAX", "BB", "BBAX", "BBBY", "BBCA", "BBCP", "BBD",
"BBDC", "BBEU", "BBH", "BBIO", "BBJP", "BBMC", "BBRE", "BBSI", "BBU",
"BBUC", "BBVA", "BBW", "BBWI", "BBY", "BC", "BCAB", "BCAT", "BCBP",
"BCC", "BCE", "BCEL", "BCI", "BCLI", "BCML", "BCO", "BCOR", "BCOV",
"BCPC", "BCRX", "BCS", "BCTX", "BDC", "BDN", "BDSI", "BDSX", "BDTX",
"BDX", "BE", "BEAM", "BECN", "BEKE", "BELFB", "BEN", "BEP", "BEPC",
"BERY", "BEST", "BETZ", "BF.A", "BF.B", "BFAM", "BFC", "BFEB", "BFH",
"BFIN", "BFLY", "BFS", "BFST", "BG", "BGCP", "BGFV", "BGS", "BGSF",
"BH", "BH.A", "BHB", "BHC", "BHE", "BHF", "BHG", "BHIL", "BHLB", "BHR",
"BHSE", "BHVN", "BIDU", "BIG", "BIGC", "BIIB", "BIL", "BILI", "BILL",
"BIO", "BIOX", "BIP", "BIPC", "BIRD", "BITF", "BITO", "BIV", "BIZD",
"BJ", "BJAN", "BJDX", "BJK", "BJRI", "BJUL", "BK", "BKCH", "BKD", "BKE",
"BKH", "BKI", "BKKT", "BKLN", "BKNG", "BKR", "BKU", "BL", "BLBD", "BLBX",
"BLCN", "BLCT", "BLD", "BLDE", "BLDP", "BLDR", "BLFS", "BLFY", "BLI",
"BLK", "BLKB", "BLL", "BLMN", "BLND", "BLNK", "BLOK", "BLPH", "BLUE",
"BLV", "BLX", "BMBL", "BMEA", "BMI", "BMO", "BMRC", "BMRN", "BMY", "BND",
"BNDX", "BNFT", "BNGO", "BNL", "BNO", "BNR", "BNS", "BNTX", "BOC",
"BOCT", "BODY", "BOH", "BOKF", "BOLT", "BON", "BOND", "BOOM", "BOOT",
"BORR", "BOTZ", "BOWL", "BOX", "BPMC", "BPMP", "BPOP", "BPRN", "BPTS",
"BQ", "BR", "BRBR", "BRC", "BRCC", "BRFS", "BRG", "BRID", "BRK.A",
"BRK.B", "BRKL", "BRKR", "BRMK", "BRO", "BROS", "BRP", "BRSP", "BRT",
"BRX", "BRY", "BRZU", "BSAC", "BSBK", "BSBR", "BSCM", "BSCN", "BSCO",
"BSGM", "BSIG", "BSJM", "BSJN", "BSJO", "BSM", "BSMX", "BSRR", "BSV",
"BSVN", "BSX", "BSY", "BTAI", "BTAL", "BTB", "BTF", "BTG", "BTRS", "BTU",
"BTWN", "BTX", "BUD", "BUFF", "BURL", "BUSE", "BV", "BVH", "BVN", "BVS",
"BW", "BWA", "BWB", "BWFG", "BWMN", "BWX", "BWXT", "BX", "BXC", "BXMT",
"BXP", "BY", "BYD", "BYND", "BYSI", "BZ", "BZH", "BZUN", "C", "CAAP",
"CABA", "CABO", "CAC", "CACC", "CACI", "CADE", "CADL", "CAE", "CAG",
"CAH", "CAJ", "CAKE", "CAL", "CALA", "CALB", "CALM", "CALT", "CALX",
"CAMP", "CANO", "CAPL", "CAR", "CARA", "CARE", "CARG", "CARR", "CARS",
"CARZ", "CASA", "CASH", "CASI", "CASS", "CASY", "CAT", "CATC", "CATO",
"CATY", "CB", "CBAN", "CBAY", "CBD", "CBFV", "CBH", "CBIO", "CBL",
"CBNK", "CBOE", "CBRE", "CBRL", "CBSH", "CBT", "CBTX", "CBU", "CBZ",
"CC", "CCB", "CCBG", "CCCC", "CCCS", "CCEP", "CCF", "CCI", "CCJ", "CCK",
"CCL", "CCMP", "CCNE", "CCO", "CCOI", "CCRN", "CCS", "CCSI", "CCU",
"CCXI", "CD", "CDAK", "CDAY", "CDE", "CDEV", "CDK", "CDLX", "CDMO",
"CDNA", "CDNS", "CDRE", "CDTX", "CDW", "CDXC", "CDXS", "CDZI", "CE",
"CECE", "CEF", "CEG", "CEIX", "CELH", "CEMI", "CENT", "CENTA", "CENX",
"CEQP", "CERE", "CERN", "CERS", "CERT", "CEVA", "CF", "CFB", "CFFI",
"CFFN", "CFG", "CFLT", "CFR", "CFRX", "CFX", "CG", "CGBD", "CGC",
"CGEM", "CGNT", "CGNX", "CGW", "CHCO", "CHCT", "CHD", "CHDN", "CHE",
"CHEF", "CHGG", "CHH", "CHIK", "CHIQ", "CHIR", "CHIS", "CHK", "CHKP",
"CHMG", "CHMI", "CHNG", "CHPT", "CHRD", "CHRS", "CHRW", "CHS", "CHTR",
"CHUY", "CHWY", "CHX", "CI", "CIA", "CIBR", "CIEN", "CIG", "CIGI",
"CIM", "CINF", "CINT", "CIO", "CIR", "CIVB", "CIVI", "CIX", "CIXX",
"CIZN", "CKPT", "CL", "CLAR", "CLAS", "CLB", "CLBK", "CLDT", "CLDX",
"CLEU", "CLF", "CLFD", "CLH", "CLIX", "CLMT", "CLNE", "CLOU", "CLOV",
"CLPR", "CLR", "CLS", "CLSK", "CLVS", "CLVT", "CLW", "CLX", "CLXT",
"CM", "CMA", "CMAX", "CMBM", "CMC", "CMCL", "CMCO", "CMCSA", "CMCT",
"CME", "CMF", "CMG", "CMI", "CMP", "CMPI", "CMPR", "CMPS", "CMRE",
"CMRX", "CMS", "CMTG", "CMTL", "CNA", "CNC", "CNCE", "CNDT", "CNEY",
"CNHI", "CNI", "CNK", "CNM", "CNMD", "CNNE", "CNO", "CNOB", "CNP",
"CNQ", "CNR", "CNRG", "CNS", "CNSL", "CNTA", "CNTB", "CNTG", "CNTY",
"CNVY", "CNX", "CNXC", "CNXN", "COCO", "CODI", "CODX", "COF", "COFS",
"COGT", "COHR", "COHU", "COIN", "COKE", "COLB", "COLD", "COLI", "COLL",
"COLM", "COMM", "COMP", "COMT", "CONE", "CONN", "CONX", "COO", "COOK",
"COOP", "COP", "COPX", "CORR", "CORS", "CORT", "COST", "COTY", "COUP",
"COUR", "COWN", "CP", "CPA", "CPB", "CPE", "CPF", "CPG", "CPI", "CPK",
"CPLG", "CPNG", "CPOP", "CPRI", "CPRT", "CPRX", "CPS", "CPSI", "CPT",
"CQP", "CQQQ", "CR", "CRAI", "CRBP", "CRBU", "CRC", "CRCT", "CRD.A",
"CRDO", "CRGE", "CRGY", "CRH", "CRHC", "CRI", "CRIS", "CRK", "CRL",
"CRM", "CRMD", "CRMT", "CRNC", "CRNX", "CRON", "CROX", "CRS", "CRSP",
"CRSR", "CRTX", "CRUS", "CRVL", "CRWD", "CS", "CSBR", "CSCO", "CSGP",
"CSGS", "CSII", "CSIQ", "CSL", "CSML", "CSQ", "CSR", "CSTE", "CSTL",
"CSTM", "CSTR", "CSV", "CSWC", "CSWI", "CSX", "CTAS", "CTBI", "CTIC",
"CTKB", "CTLP", "CTLT", "CTMX", "CTO", "CTOS", "CTRA", "CTRE", "CTRN",
"CTS", "CTSH", "CTSO", "CTT", "CTVA", "CTXS", "CUBE", "CUBI", "CUE",
"CUK", "CURI", "CURO", "CURV", "CUTR", "CUZ", "CVAC", "CVBF", "CVCO",
"CVCY", "CVE", "CVET", "CVGW", "CVI", "CVLG", "CVLT", "CVLY", "CVM",
"CVNA", "CVRX", "CVS", "CVT", "CVX", "CW", "CWB", "CWBR", "CWCO",
"CWEB", "CWEN", "CWEN.A", "CWH", "CWI", "CWK", "CWST", "CWT", "CX",
"CXM", "CXSE", "CXW", "CYBE", "CYBR", "CYCN", "CYH", "CYRX", "CYT",
"CYTK", "CZNC", "CZR", "D", "DAC", "DADA", "DAKT", "DAL", "DAN", "DAO",
"DAR", "DASH", "DATS", "DAWN", "DB", "DBA", "DBC", "DBD", "DBEF", "DBGI",
"DBI", "DBMF", "DBO", "DBRG", "DBTX", "DBVT", "DBX", "DCBO", "DCGO",
"DCI", "DCO", "DCOM", "DCP", "DCPH", "DCT", "DD", "DDD", "DDL", "DDM",
"DDOG", "DDS", "DDWM", "DE", "DEA", "DECK", "DEI", "DELL", "DEM", "DEN",
"DENN", "DES", "DESP", "DFAC", "DFEN", "DFH", "DFIN", "DFND", "DFNL",
"DFS", "DG", "DGICA", "DGII", "DGRO", "DGRS", "DGRW", "DGS", "DGX", "DH",
"DHC", "DHHC", "DHI", "DHIL", "DHR", "DHT", "DHX", "DIA", "DIBS", "DICE",
"DIDI", "DIN", "DINO", "DIOD", "DIS", "DISCA", "DISCB", "DISCK", "DISH",
"DJCO", "DJP", "DK", "DKL", "DKNG", "DKS", "DLB", "DLN", "DLO", "DLR",
"DLS", "DLTH", "DLTR", "DLX", "DM", "DMLP", "DMRC", "DMRL", "DMTK",
"DNA", "DNAY", "DNB", "DNL", "DNLI", "DNMR", "DNN", "DNOW", "DNP",
"DNUT", "DO", "DOC", "DOCN", "DOCS", "DOCU", "DOG", "DOLE", "DOMA",
"DOMO", "DON", "DOOO", "DOOR", "DORM", "DOUG", "DOV", "DOW", "DOX",
"DOYU", "DPST", "DPZ", "DRE", "DRH", "DRI", "DRIP", "DRIV", "DRMA",
"DRQ", "DRRX", "DRSK", "DRVN", "DSEP", "DSEY", "DSGN", "DSGX", "DSI",
"DSKE", "DSP", "DT", "DTC", "DTE", "DTEC", "DTIL", "DTM", "DUK", "DUOL",
"DUST", "DV", "DVA", "DVAX", "DVN", "DVY", "DVYE", "DWAS", "DWM", "DX",
"DXC", "DXCM", "DXD", "DXJ", "DXLG", "DXPE", "DY", "DYAI", "DYN", "DYNS",
"DZSI", "E", "EA", "EAF", "EAR", "EARN", "EAT", "EB", "EBAY", "EBC",
"EBET", "EBF", "EBIX", "EBIZ", "EBMT", "EBND", "EBON", "EBR", "EBS",
"EBTC", "EC", "ECH", "ECL", "ECOL", "ECOM", "ECON", "ECPG", "ECVT",
"ED", "EDC", "EDIT", "EDOC", "EDR", "EDRY", "EDTK", "EDU", "EDV", "EE",
"EEFT", "EEIQ", "EEM", "EEMA", "EEMV", "EEX", "EFA", "EFAV", "EFC",
"EFG", "EFSC", "EFTR", "EFV", "EFX", "EGAN", "EGBN", "EGHT", "EGIO",
"EGLE", "EGO", "EGP", "EGRX", "EGY", "EHAB", "EHC", "EHTH", "EIDO", "EIG",
"EIGR", "EIX", "EL", "ELA", "ELAN", "ELEV", "ELF", "ELMD", "ELME", "ELMS",
"ELOX", "ELP", "ELS", "ELV", "ELY", "ELYM", "EM", "EMB", "EMBC", "EME",
"EMGF", "EML", "EMLC", "EMLP", "EMN", "EMP", "EMQQ", "EMR", "EMTY",
"EMXC", "ENB", "ENDP", "ENFN", "ENIA", "ENIC", "ENLC", "ENOB", "ENOV",
"ENPC", "ENPH", "ENR", "ENS", "ENSG", "ENTA", "ENTG", "ENV", "ENVA",
"ENVX", "ENZ", "EOG", "EOLS", "EOSE", "EPAC", "EPAM", "EPAY", "EPC",
"EPD", "EPI", "EPIX", "EPM", "EPOL", "EPP", "EPR", "EPRF", "EPRT", "EPU",
"EPZM", "EQ", "EQBK", "EQC", "EQH", "EQIX", "EQOS", "EQR", "EQRX", "EQT",
"EQX", "ERAS", "ERF", "ERIC", "ERIE", "ERII", "ERUS", "ERX", "ERY", "ES",
"ESAB", "ESBA", "ESCA", "ESE", "ESGD", "ESGE", "ESGR", "ESGU", "ESGV",
"ESI", "ESLT", "ESMT", "ESNT", "ESPO", "ESPR", "ESQ", "ESRT", "ESS",
"ESSA", "ESTA", "ESTC", "ESTE", "ET", "ETD", "ETN", "ETNB", "ETON",
"ETR", "ETRN", "ETSY", "ETWO", "EUFN", "EUO", "EURN", "EVA", "EVAX",
"EVBG", "EVBN", "EVC", "EVCM", "EVER", "EVFM", "EVGO", "EVH", "EVI",
"EVLO", "EVLV", "EVOP", "EVR", "EVRG", "EVRI", "EVTC", "EW", "EWA",
"EWBC", "EWC", "EWCO", "EWCZ", "EWG", "EWH", "EWI", "EWJ", "EWL", "EWM",
"EWP", "EWQ", "EWS", "EWT", "EWTX", "EWU", "EWW", "EWX", "EWY", "EWZ",
"EXAS", "EXC", "EXEL", "EXFY", "EXG", "EXI", "EXK", "EXLS", "EXP",
"EXPD", "EXPE", "EXPI", "EXPO", "EXPR", "EXR", "EXTN", "EXTR", "EYE",
"EZA", "EZGO", "EZPW", "EZU", "F", "FA", "FAF", "FALN", "FAMI", "FAN",
"FANG", "FARM", "FARO", "FAS", "FAST", "FATE", "FAZ", "FBC", "FBHS",
"FBIN", "FBIO", "FBIZ", "FBK", "FBMS", "FBNC", "FBND", "FBP", "FBRT",
"FBT", "FC", "FCAP", "FCBC", "FCCO", "FCEL", "FCF", "FCFS", "FCG", "FCN",
"FCNCA", "FCOM", "FCPT", "FCX", "FDBC", "FDIS", "FDL", "FDM", "FDMT",
"FDN", "FDNI", "FDP", "FDS", "FDX", "FE", "FEAM", "FELE", "FEM", "FEMY",
"FENC", "FENY", "FEZ", "FF", "FFBC", "FFIC", "FFIE", "FFIN", "FFIV",
"FFWM", "FG", "FGBI", "FGEN", "FHB", "FHI", "FHLC", "FHN", "FHS", "FHTX",
"FIBK", "FICO", "FIDU", "FIGS", "FINM", "FINX", "FIS", "FISI", "FISK",
"FISV", "FITB", "FIVE", "FIVG", "FIVN", "FIW", "FIX", "FIXD", "FIXX",
"FIZZ", "FJUL", "FL", "FLCB", "FLDM", "FLEX", "FLGT", "FLIC", "FLJP",
"FLMN", "FLNC", "FLNG", "FLNT", "FLO", "FLOT", "FLOW", "FLQL", "FLR",
"FLRU", "FLS", "FLSP", "FLT", "FLWS", "FLYW", "FM", "FMAO", "FMB", "FMBH",
"FMC", "FMF", "FMNB", "FMS", "FMTX", "FN", "FNA", "FNB", "FNCB", "FNCH",
"FNCL", "FND", "FNDA", "FNDC", "FNDE", "FNDF", "FNDX", "FNF", "FNGU",
"FNHC", "FNKO", "FNLC", "FNV", "FNWB", "FOCS", "FOE", "FOLD", "FONR",
"FOR", "FORG", "FORM", "FORR", "FOSL", "FOUR", "FOX", "FOXA", "FOXF",
"FPE", "FPEI", "FPH", "FPI", "FPL", "FPX", "FPXI", "FR", "FRAF", "FRBA",
"FRBK", "FRC", "FREL", "FREQ", "FREY", "FRG", "FRGI", "FRHC", "FRLN",
"FRME", "FRO", "FROG", "FRPH", "FRPT", "FRSH", "FRST", "FRT", "FRTA",
"FSBC", "FSBW", "FSEP", "FSFG", "FSLR", "FSLY", "FSM", "FSP", "FSR",
"FSS", "FSSI", "FSTA", "FSTR", "FSV", "FTAI", "FTCH", "FTCI", "FTCS",
"FTDR", "FTEC", "FTGC", "FTHM", "FTI", "FTLS", "FTNT", "FTS", "FTSL",
"FTSM", "FTV", "FTXG", "FTXR", "FUBO", "FUL", "FULC", "FULT", "FUN",
"FUNC", "FUSN", "FUTU", "FUV", "FVCB", "FVD", "FVRR", "FWONA", "FWONK",
"FWRD", "FXA", "FXD", "FXE", "FXG", "FXH", "FXI", "FXL", "FXLV", "FXO",
"FXR", "FXY", "FYBR", "FYC", "FYT", "FYX", "G", "GABC", "GAIA", "GAL",
"GALT", "GAMB", "GAN", "GANX", "GATO", "GATX", "GBCI", "GBIL", "GBIO",
"GBL", "GBLI", "GBT", "GBX", "GCBC", "GCI", "GCMG", "GCO", "GCP", "GD",
"GDDY", "GDEN", "GDOT", "GDRX", "GDS", "GDX", "GDXJ", "GDYN", "GE", "GEF",
"GEF.B", "GEHC", "GEL", "GEM", "GEN", "GENC", "GENI", "GEO", "GERN",
"GES", "GEVO", "GFF", "GFI", "GFL", "GFS", "GGAL", "GGB", "GGG", "GGPI",
"GH", "GHC", "GHL", "GHLD", "GHM", "GHRS", "GIB", "GIC", "GIII", "GIL",
"GILD", "GILT", "GIS", "GIW", "GKOS", "GL", "GLBE", "GLD", "GLDD", "GLDM",
"GLNG", "GLOB", "GLP", "GLPI", "GLRE", "GLSI", "GLT", "GLTO", "GLTR",
"GLUE", "GLW", "GLYC", "GM", "GMAB", "GME", "GMED", "GMF", "GMRE",
"GMS", "GNE", "GNK", "GNL", "GNLN", "GNOG", "GNPX", "GNR", "GNRC",
"GNSS", "GNTX", "GNTY", "GNUS", "GNW", "GO", "GOCO", "GOED", "GOEV",
"GOGL", "GOGO", "GOLD", "GOLF", "GOOD", "GOOG", "GOOGL", "GOOS", "GORO",
"GOSS", "GOVT", "GP", "GPC", "GPI", "GPK", "GPMT", "GPN", "GPOR", "GPRE",
"GPRK", "GPRO", "GPS", "GQRE", "GRAY", "GRBK", "GRC", "GRCL", "GREE",
"GRFS", "GRIL", "GRMN", "GROY", "GRPH", "GRPN", "GRTS", "GRTX", "GRUB",
"GRVI", "GRWG", "GS", "GSAT", "GSBC", "GSEV", "GSG", "GSHD", "GSIE",
"GSIT", "GSKY", "GSL", "GSLC", "GSM", "GSSC", "GSY", "GT", "GTES",
"GTH", "GTHX", "GTLB", "GTLS", "GTN", "GTO", "GTPA", "GTX", "GTY",
"GTYH", "GUNR", "GUSH", "GVA", "GVI", "GWGH", "GWH", "GWRE", "GWRS",
"GWW", "GWX", "GXC", "GXO", "GYRO", "H", "HA", "HACK", "HAE", "HAFC",
"HAIL", "HAIN", "HAL", "HALO", "HARP", "HAS", "HASI", "HAUZ", "HAYN",
"HAYW", "HBAN", "HBB", "HBCP", "HBI", "HBIO", "HBM", "HBNC", "HBT",
"HCA", "HCAT", "HCC", "HCCI", "HCDI", "HCI", "HCKT", "HCSG", "HCWB",
"HD", "HDG", "HDGE", "HDSN", "HDV", "HE", "HEAR", "HEEM", "HEES", "HEI",
"HEI.A", "HELE", "HEP", "HEPS", "HERO", "HES", "HESM", "HEWJ", "HEXO",
"HFC", "HFFG", "HFWA", "HGEN", "HGV", "HHC", "HI", "HIBB", "HIFS", "HIG",
"HII", "HIMS", "HIPO", "HIVE", "HIW", "HL", "HLF", "HLI", "HLIO", "HLIT",
"HLMN", "HLNE", "HLT", "HLTH", "HLVX", "HLX", "HMHC", "HMLP", "HMN",
"HMST", "HMTV", "HNDL", "HNGR", "HNI", "HNST", "HOFT", "HOG", "HOLI",
"HOLX", "HOMB", "HON", "HONE", "HOOD", "HOOK", "HOPE", "HOUS", "HOV",
"HOWL", "HP", "HPE", "HPK", "HPP", "HPQ", "HPX", "HQY", "HR", "HRB",
"HRI", "HRL", "HRMY", "HROW", "HRT", "HRTG", "HRTX", "HSC", "HSIC",
"HSII", "HSKA", "HST", "HSTM", "HSY", "HT", "HTA", "HTBI", "HTBK",
"HTH", "HTHT", "HTLD", "HTLF", "HTUS", "HTZ", "HUBB", "HUBG", "HUBS",
"HUDI", "HUIZ", "HUM", "HUN", "HURC", "HURN", "HUT", "HUYA", "HVT",
"HWBK", "HWC", "HWKN", "HWM", "HXL", "HY", "HYD", "HYEM", "HYFM", "HYG",
"HYLB", "HYLN", "HYLS", "HYMB", "HYS", "HYW", "HYZN", "HZNP", "HZO",
"IAA", "IAC", "IAG", "IAGG", "IAI", "IART", "IAS", "IAT", "IAU", "IBB",
"IBCP", "IBDN", "IBDO", "IBDP", "IBER", "IBEX", "IBIO", "IBKR", "IBM",
"IBN", "IBOC", "IBP", "IBRX", "IBTX", "IBUY", "ICAD", "ICE", "ICF",
"ICFI", "ICHR", "ICL", "ICLN", "ICLR", "ICPT", "ICSH", "ICUI", "ICVT",
"ICVX", "IDA", "IDCC", "IDEV", "IDEX", "IDN", "IDT", "IDU", "IDV",
"IDXX", "IDYA", "IE", "IECS", "IEF", "IEFA", "IEI", "IEMG", "IEP",
"IESC", "IETC", "IEUR", "IEUS", "IEV", "IEX", "IFBD", "IFF", "IFGL",
"IFS", "IGE", "IGIB", "IGLB", "IGM", "IGMS", "IGSB", "IGT", "IGV", "IH",
"IHDG", "IHE", "IHF", "IHG", "IHI", "IHRT", "IHS", "III", "IIIN", "IIIV",
"IIN", "IINN", "IIPR", "IIVI", "IJH", "IJJ", "IJK", "IJR", "IJS", "IJT",
"IKNA", "IKT", "ILF", "ILMN", "ILPT", "IMAB", "IMAX", "IMCR", "IMGN",
"IMGO", "IMKTA", "IMMR", "IMNM", "IMO", "IMPL", "IMRA", "IMRX", "IMUX",
"IMVT", "IMXI", "INAB", "INBK", "INBX", "INCO", "INCY", "INDA", "INDB",
"INDI", "INDS", "INDT", "INDY", "INFA", "INFN", "INFU", "INFY", "ING",
"INGN", "INGR", "INMD", "INN", "INNV", "INO", "INSE", "INSG", "INSM",
"INSP", "INST", "INSW", "INT", "INTA", "INTC", "INTU", "INTZ", "INVA",
"INVH", "INVZ", "INZY", "IONQ", "IONS", "IOO", "IOSP", "IOVA", "IP",
"IPAC", "IPAR", "IPAY", "IPG", "IPGP", "IPI", "IPSC", "IPW", "IQ",
"IQDE", "IQDF", "IQDG", "IQLT", "IQV", "IR", "IRBO", "IRBT", "IRDM",
"IRM", "IRMD", "IRT", "IRTC", "IRWD", "IS", "ISBC", "ISEE", "ISMD",
"ISPC", "ISRA", "ISRG", "ISTB", "ISTR", "IT", "ITA", "ITB", "ITCI",
"ITEQ", "ITGR", "ITI", "ITIC", "ITM", "ITOS", "ITOT", "ITRI", "ITRN",
"ITT", "ITUB", "ITW", "IUSB", "IUSG", "IUSV", "IVA", "IVAC", "IVC",
"IVE", "IVES", "IVLU", "IVOL", "IVOO", "IVR", "IVT", "IVV", "IVW", "IVZ",
"IWB", "IWC", "IWD", "IWF", "IWL", "IWM", "IWN", "IWO", "IWP", "IWR",
"IWS", "IWV", "IWX", "IWY", "IXC", "IXG", "IXJ", "IXN", "IXP", "IXUS",
"IYC", "IYE", "IYF", "IYG", "IYH", "IYJ", "IYK", "IYLD", "IYM", "IYR",
"IYT", "IYW", "IYY", "IYZ", "IZRL", "J", "JAAA", "JACK", "JAMF", "JANX",
"JAZZ", "JBGS", "JBHT", "JBI", "JBL", "JBLU", "JBSS", "JBT", "JCI",
"JD", "JDST", "JEF", "JELD", "JEPI", "JETS", "JHEM", "JHG", "JHMD",
"JHMM", "JHMS", "JHMT", "JJSF", "JKHY", "JLL", "JMSB", "JNCE", "JNJ",
"JNK", "JNPR", "JNUG", "JOAN", "JOBY", "JOE", "JOUT", "JP", "JPHY",
"JPIN", "JPM", "JPSE", "JPST", "JRVR", "JSML", "JUPW", "JW.A", "JWEL",
"JWN", "JXN", "JYNT", "JZXN", "K", "KAI", "KALA", "KALU", "KALV", "KAMN",
"KAR", "KARO", "KBA", "KBAL", "KBE", "KBH", "KBNT", "KBR", "KBWB", "KBWD",
"KBWP", "KBWY", "KC", "KD", "KDNY", "KDP", "KE", "KELYA", "KEMQ", "KEN",
"KERN", "KEX", "KEY", "KEYS", "KFRC", "KFY", "KGC", "KHC", "KIDS", "KIE",
"KIM", "KIND", "KINZ", "KKR", "KLAC", "KLDO", "KLIC", "KLTR", "KLXE",
"KMB", "KMI", "KMLM", "KMPR", "KMT", "KMX", "KN", "KNOP", "KNSA", "KNSL",
"KNTE", "KNTK", "KNX", "KO", "KOD", "KODK", "KOIN", "KOMP", "KOP", "KOPN",
"KOS", "KPLT", "KPTI", "KR", "KRA", "KRBN", "KRBP", "KRC", "KRE", "KREF",
"KRG", "KRMD", "KRNL", "KRNT", "KRNY", "KRO", "KRON", "KROS", "KRP",
"KRT", "KRTX", "KRUS", "KRYS", "KSS", "KT", "KTB", "KTOS", "KUKE", "KULR",
"KURA", "KVHI", "KW", "KWEB", "KWR", "KXI", "KYMR", "KZR", "L", "LABD",
"LABP", "LABU", "LAC", "LAD", "LADR", "LAKE", "LAMR", "LANC", "LAND",
"LARK", "LASR", "LAUR", "LAW", "LAWS", "LAZ", "LAZR", "LBAI", "LBC",
"LBPH", "LBRDA", "LBRDK", "LBRT", "LBTYA", "LBTYB", "LBTYK", "LC", "LCI",
"LCID", "LCII", "LCNB", "LCUT", "LDEM", "LDI", "LDOS", "LDUR", "LE",
"LEA", "LEAP", "LECO", "LEG", "LEGH", "LEGN", "LEGR", "LEN", "LEN.B",
"LESL", "LEV", "LEVI", "LEVL", "LFCR", "LFG", "LFST", "LFUS", "LFVN",
"LGF.A", "LGF.B", "LGIH", "LGND", "LGVN", "LH", "LHCG", "LHDX", "LHX",
"LI", "LICY", "LIFE", "LII", "LILA", "LILAK", "LILM", "LIN", "LIND",
"LIT", "LITE", "LIVN", "LJPC", "LKFN", "LKQ", "LL", "LLNW", "LLY", "LMAT",
"LMBS", "LMND", "LMNR", "LMST", "LMT", "LNC", "LNDC", "LNG", "LNN",
"LNSR", "LNT", "LNTH", "LNW", "LOB", "LOCO", "LOGC", "LOGI", "LOPE",
"LOUP", "LOVE", "LOW", "LPG", "LPI", "LPL", "LPLA", "LPRO", "LPSN",
"LPX", "LQD", "LQDA", "LQDH", "LQDT", "LRCX", "LRN", "LRNZ", "LSCC",
"LSF", "LSI", "LSPD", "LSTR", "LSXMA", "LSXMB", "LSXMK", "LTC", "LTCH",
"LTH", "LTHM", "LTL", "LTPZ", "LTRN", "LTRPA", "LTRPB", "LU", "LULU",
"LUMN", "LUNA", "LUNG", "LUV", "LVOX", "LVRA", "LVS", "LVTX", "LW",
"LWLG", "LXEH", "LXFR", "LXP", "LXRX", "LXU", "LYB", "LYEL", "LYFT",
"LYG", "LYLT", "LYRA", "LYTS", "LYV", "LZ", "LZB", "M", "MA", "MAA",
"MAC", "MACC", "MAG", "MAIN", "MAN", "MANH", "MANT", "MANU", "MAPS",
"MAR", "MARA", "MARB", "MAS", "MASI", "MASS", "MAT", "MATV", "MATW",
"MATX", "MAX", "MAXN", "MAXR", "MBB", "MBC", "MBCN", "MBI", "MBII",
"MBIN", "MBIO", "MBT", "MBUU", "MBWM", "MC", "MCB", "MCBC", "MCBS",
"MCD", "MCFT", "MCG", "MCHI", "MCHP", "MCK", "MCO", "MCRB", "MCRI",
"MCS", "MCW", "MCY", "MD", "MDB", "MDC", "MDGL", "MDIV", "MDLZ", "MDRX",
"MDT", "MDU", "MDWT", "MDXG", "MDY", "MDYG", "MDYV", "ME", "MEC", "MED",
"MEDP", "MEDS", "MEG", "MEI", "MEIP", "MELI", "MEOH", "MERC", "MESA",
"MET", "META", "METC", "METX", "MF", "MFA", "MFC", "MFEM", "MFG", "MFGP",
"MG", "MGA", "MGC", "MGEE", "MGI", "MGIC", "MGK", "MGM", "MGNI", "MGNX",
"MGP", "MGPI", "MGRC", "MGTA", "MGTX", "MGV", "MGY", "MHH", "MHK", "MHO",
"MIC", "MIDD", "MILE", "MIME", "MINT", "MIR", "MIRM", "MIRO", "MITK",
"MITQ", "MJ", "MKC", "MKFG", "MKL", "MKSI", "MKTW", "MKTX", "ML", "MLAB",
"MLCO", "MLI", "MLKN", "MLM", "MLNK", "MLP", "MLPA", "MLPX", "MLR",
"MLSS", "MLYS", "MMAT", "MMC", "MMI", "MMM", "MMP", "MMS", "MMSI",
"MMX", "MMYT", "MNA", "MNDT", "MNDY", "MNKD", "MNMD", "MNOV", "MNRL",
"MNRO", "MNSB", "MNSO", "MNST", "MNTK", "MNTS", "MNTV", "MO", "MOAT",
"MOD", "MODG", "MODN", "MODV", "MOFG", "MOG.A", "MOGO", "MOH", "MOLN",
"MOMO", "MOO", "MOON", "MORF", "MORN", "MORT", "MOS", "MOV", "MOVE",
"MP", "MPAA", "MPB", "MPC", "MPLN", "MPLX", "MPW", "MPWR", "MPX", "MQ",
"MRAI", "MRBK", "MRC", "MRCY", "MRGR", "MRK", "MRKR", "MRM", "MRNA",
"MRNS", "MRO", "MRSN", "MRTN", "MRTX", "MRUS", "MRVI", "MRVL", "MS",
"MSA", "MSBI", "MSCI", "MSEX", "MSFT", "MSGE", "MSGM", "MSGS", "MSI",
"MSM", "MSOS", "MSP", "MSTR", "MSVX", "MT", "MTB", "MTCH", "MTCR", "MTD",
"MTDR", "MTEM", "MTG", "MTH", "MTN", "MTOR", "MTRN", "MTRX", "MTSI",
"MTTR", "MTUM", "MTW", "MTX", "MTZ", "MU", "MUB", "MULN", "MUR", "MUSA",
"MVBF", "MVIS", "MVST", "MVV", "MWA", "MX", "MXCT", "MXI", "MXL", "MYE",
"MYFW", "MYGN", "MYOV", "MYPS", "MYRG", "MYTE", "NABL", "NAD", "NAIL",
"NANR", "NAPA", "NARI", "NAT", "NATH", "NATI", "NATR", "NAUT", "NAVI",
"NBEV", "NBHC", "NBIX", "NBN", "NBR", "NBSE", "NBTB", "NBTX", "NC",
"NCBS", "NCLH", "NCMI", "NCNO", "NCR", "NDAQ", "NDLS", "NDSN", "NE",
"NEA", "NEAR", "NEE", "NEGG", "NEM", "NEO", "NEOG", "NEP", "NERD",
"NERV", "NESR", "NET", "NEU", "NEWR", "NEWT", "NEX", "NEXA", "NEXI",
"NEXT", "NFBK", "NFE", "NFG", "NFLX", "NG", "NGD", "NGG", "NGM", "NGMS",
"NGVC", "NGVT", "NH", "NHC", "NHI", "NI", "NIC", "NIO", "NISN", "NJR",
"NKE", "NKLA", "NKSH", "NKTR", "NKTX", "NL", "NLOK", "NLS", "NLSN",
"NLSP", "NLTX", "NLY", "NMFC", "NMIH", "NMM", "NMR", "NMRD", "NMRK",
"NNBR", "NNI", "NNN", "NNOX", "NOA", "NOBL", "NOC", "NODK", "NOG", "NOK",
"NOMD", "NOTV", "NOV", "NOVA", "NOVT", "NOW", "NP", "NPK", "NPO", "NPTN",
"NR", "NRBO", "NRC", "NRDS", "NREF", "NRG", "NRGU", "NRIM", "NRIX",
"NRZ", "NS", "NSA", "NSC", "NSIT", "NSP", "NSSC", "NSTG", "NTAP", "NTB",
"NTCO", "NTCT", "NTES", "NTGR", "NTLA", "NTNX", "NTP", "NTR", "NTRA",
"NTRS", "NTST", "NTSX", "NTUS", "NUAN", "NUE", "NUGO", "NUGT", "NUS",
"NUSI", "NUTX", "NUV", "NUVA", "NUVB", "NUVL", "NVAX", "NVCR", "NVDA",
"NVEC", "NVEE", "NVG", "NVGS", "NVMI", "NVR", "NVRO", "NVST", "NVT",
"NVTA", "NVTS", "NWBI", "NWE", "NWFL", "NWL", "NWLI", "NWN", "NWPX",
"NWS", "NWSA", "NX", "NXE", "NXGN", "NXPI", "NXRT", "NXST", "NXT",
"NXTC", "NXTG", "NYCB", "NYMT", "NYMX", "NYT", "NYXH", "O", "OABI",
"OAS", "OB", "OBNK", "OC", "OCDX", "OCFC", "OCFT", "OCG", "OCGN", "OCSL",
"OCUL", "OCX", "ODC", "ODFL", "ODP", "OEC", "OEF", "OESX", "OFC", "OFED",
"OFG", "OFIX", "OFLX", "OG", "OGCP", "OGE", "OGI", "OGN", "OGS", "OHI",
"OI", "OIH", "OII", "OIS", "OKE", "OKTA", "OLED", "OLK", "OLLI", "OLMA",
"OLN", "OLO", "OLP", "OLPX", "OM", "OMC", "OMCL", "OMER", "OMF", "OMFL",
"OMFS", "OMGA", "OMI", "OMIC", "ON", "ONB", "ONCR", "ONE", "ONEM", "ONEQ",
"ONEW", "ONL", "ONLN", "ONON", "ONTF", "ONTO", "OOMA", "OPBK", "OPCH",
"OPEN", "OPI", "OPK", "OPRT", "OPRX", "OPT", "OPTN", "OPY", "OR", "ORA",
"ORAN", "ORC", "ORCC", "ORCL", "ORGN", "ORGO", "ORGS", "ORI", "ORIC",
"ORLA", "ORLY", "ORPH", "ORRF", "OSBC", "OSCR", "OSG", "OSH", "OSIS",
"OSK", "OSPN", "OSTK", "OSUR", "OSW", "OTEX", "OTIS", "OTLY", "OTTR",
"OUNZ", "OUST", "OUT", "OVBC", "OVID", "OVLY", "OVV", "OWL", "OXM",
"OXY", "OYST", "OZK", "PAA", "PAAS", "PACB", "PACK", "PACW", "PAG",
"PAGS", "PAHC", "PALL", "PANW", "PAPR", "PAR", "PARA", "PARR", "PASG",
"PATH", "PATK", "PAVE", "PAVM", "PAX", "PAY", "PAYA", "PAYC", "PAYO",
"PAYS", "PAYX", "PB", "PBA", "PBCT", "PBD", "PBE", "PBF", "PBFS", "PBFX",
"PBH", "PBI", "PBIP", "PBJ", "PBS", "PBTS", "PBW", "PBYI", "PCAR", "PCB",
"PCEF", "PCG", "PCH", "PCOR", "PCRX", "PCSB", "PCT", "PCTI", "PCTY",
"PCVX", "PCY", "PCYG", "PCYO", "PD", "PDBC", "PDCE", "PDCO", "PDD",
"PDFS", "PDLB", "PDM", "PDN", "PDP", "PDS", "PEAK", "PEB", "PEBK",
"PEBO", "PECO", "PEG", "PEGA", "PEJ", "PEN", "PENN", "PEP", "PEPG",
"PERI", "PETQ", "PETS", "PETV", "PETZ", "PEZ", "PFBC", "PFC", "PFE",
"PFEB", "PFF", "PFFA", "PFFD", "PFFR", "PFFV", "PFG", "PFGC", "PFHC",
"PFHD", "PFIS", "PFS", "PFSI", "PFSW", "PFXF", "PG", "PGC", "PGEN",
"PGF", "PGNY", "PGR", "PGRE", "PGTI", "PGX", "PH", "PHAR", "PHAS",
"PHAT", "PHG", "PHM", "PHO", "PHR", "PHVS", "PHYS", "PI", "PICK", "PID",
"PII", "PINC", "PINE", "PING", "PINS", "PIO", "PIPR", "PIRS", "PJAN",
"PJP", "PJT", "PJUL", "PK", "PKBK", "PKE", "PKG", "PKI", "PKOH", "PL",
"PLAB", "PLAN", "PLAY", "PLBC", "PLBY", "PLCE", "PLD", "PLL", "PLMR",
"PLNT", "PLOW", "PLPC", "PLRX", "PLSE", "PLTK", "PLTR", "PLUG", "PLUS",
"PLXS", "PLYA", "PLYM", "PM", "PMT", "PMVP", "PNC", "PNFP", "PNM",
"PNR", "PNRG", "PNT", "PNTG", "PNTM", "PNW", "POCT", "PODD", "POLY",
"POND", "POOL", "POR", "POSH", "POST", "POW", "POWI", "POWL", "POWW",
"PPA", "PPBI", "PPC", "PPG", "PPGH", "PPL", "PPLT", "PPTY", "PR", "PRA",
"PRAA", "PRAX", "PRCH", "PRCT", "PRDO", "PREF", "PRF", "PRFT", "PRFX",
"PRFZ", "PRG", "PRGO", "PRGS", "PRI", "PRIM", "PRK", "PRLB", "PRLD",
"PRM", "PRMW", "PRNT", "PRO", "PROG", "PROV", "PRPL", "PRTA", "PRTH",
"PRTK", "PRTS", "PRTY", "PRU", "PRVA", "PRVB", "PSA", "PSB", "PSC",
"PSCC", "PSCH", "PSCI", "PSCT", "PSFE", "PSK", "PSL", "PSMT", "PSN",
"PSNL", "PSO", "PSP", "PSPC", "PSQ", "PSTG", "PSTH", "PSTL", "PSTX",
"PSX", "PSXP", "PTC", "PTCT", "PTEN", "PTF", "PTGX", "PTH", "PTLC",
"PTLO", "PTMC", "PTNQ", "PTON", "PTRA", "PTSI", "PTVE", "PUBM", "PUK",
"PUMP", "PVBC", "PVG", "PVH", "PWFL", "PWOD", "PWP", "PWR", "PWSC",
"PXD", "PXF", "PXH", "PXLW", "PYCR", "PYPD", "PYPL", "PYR", "PZA", "PZN",
"PZZA", "QABA", "QAI", "QCLN", "QCOM", "QCRH", "QDEL", "QDF", "QED",
"QEMM", "QGEN", "QH", "QID", "QLD", "QLS", "QLTA", "QLYS", "QMCO", "QMN",
"QNST", "QQEW", "QQQ", "QQQJ", "QQQM", "QRTEA", "QRTEB", "QRVO", "QS",
"QSI", "QSR", "QTEC", "QTNT", "QTRX", "QTUM", "QTWO", "QUAD", "QUAL",
"QUOT", "QURE", "QYLD", "R", "RAAS", "RACE", "RAD", "RADI", "RAIN",
"RAMP", "RANI", "RAPT", "RARE", "RBA", "RBB", "RBBN", "RBC", "RBCAA",
"RBLX", "RBOT", "RC", "RCAT", "RCD", "RCI", "RCII", "RCKT", "RCKY",
"RCL", "RCM", "RCUS", "RDFN", "RDN", "RDNT", "RDUS", "RDVT", "RDVY",
"RDWR", "RE", "REAL", "REET", "REFR", "REG", "REGI", "REGN", "RELY",
"REM", "REMX", "RENT", "REPH", "REPL", "REPX", "RES", "RESN", "RETA",
"RETL", "REV", "REVG", "REW", "REX", "REXR", "REYN", "REZ", "REZI", "RF",
"RFL", "RFP", "RGA", "RGC", "RGCO", "RGEN", "RGI", "RGLD", "RGNX", "RGP",
"RGR", "RGS", "RH", "RHI", "RHP", "RHS", "RICK", "RIDE", "RIG", "RIGL",
"RILY", "RING", "RIOT", "RITM", "RIVN", "RJF", "RKLB", "RKT", "RL",
"RLAY", "RLGT", "RLGY", "RLI", "RLJ", "RLMD", "RLX", "RLY", "RLYB",
"RM", "RMAX", "RMBI", "RMBS", "RMD", "RMNI", "RMO", "RMR", "RMTI",
"RNA", "RNAZ", "RNG", "RNLX", "RNR", "RNST", "RNW", "RNXT", "ROAD",
"ROBO", "ROCC", "ROCK", "ROG", "ROIC", "ROIV", "ROK", "ROKU", "ROL",
"ROLL", "ROM", "ROOT", "ROP", "ROST", "ROVR", "RPAR", "RPAY", "RPD",
"RPG", "RPHM", "RPID", "RPM", "RPRX", "RPT", "RPTX", "RPV", "RRBI",
"RRC", "RRGB", "RRR", "RRX", "RS", "RSG", "RSI", "RSKD", "RSP", "RSX",
"RSXJ", "RTH", "RTM", "RTX", "RUBY", "RUN", "RUSHA", "RUSHB", "RUSL",
"RUTH", "RVI", "RVLV", "RVMD", "RVNC", "RVP", "RVSB", "RWJ", "RWM",
"RWO", "RWR", "RWT", "RWX", "RXDX", "RXI", "RXRX", "RXST", "RXT", "RY",
"RYAAY", "RYAM", "RYAN", "RYF", "RYH", "RYI", "RYLD", "RYN", "RYT",
"RYTM", "RZG", "RZV", "S", "SA", "SABR", "SAFE", "SAFM", "SAFT", "SAGE",
"SAH", "SAIA", "SAIC", "SAL", "SAM", "SAMG", "SAN", "SANA", "SAND",
"SANM", "SASR", "SATS", "SAVA", "SAVE", "SB", "SBAC", "SBCF", "SBFG",
"SBGI", "SBH", "SBII", "SBIO", "SBLK", "SBNY", "SBOW", "SBRA", "SBS",
"SBSI", "SBSW", "SBT", "SBTX", "SBUX", "SCCO", "SCHA", "SCHB", "SCHC",
"SCHE", "SCHF", "SCHG", "SCHH", "SCHK", "SCHL", "SCHM", "SCHN", "SCHO",
"SCHP", "SCHR", "SCHV", "SCHW", "SCHZ", "SCI", "SCL", "SCO", "SCOR",
"SCPH", "SCPL", "SCPS", "SCS", "SCSC", "SCU", "SCVL", "SCVX", "SCWX",
"SCZ", "SD", "SDC", "SDGR", "SDOW", "SDS", "SDY", "SE", "SEAC", "SEAS",
"SEAT", "SEB", "SEDG", "SEE", "SEER", "SEIC", "SELB", "SEM", "SEMR",
"SENEA", "SENS", "SERA", "SF", "SFBS", "SFE", "SFIX", "SFL", "SFM",
"SFNC", "SFST", "SFT", "SG", "SGA", "SGC", "SGEN", "SGFY", "SGH", "SGHT",
"SGMO", "SGMS", "SGOL", "SGRY", "SGTX", "SH", "SHAK", "SHBI", "SHC",
"SHCR", "SHEN", "SHLS", "SHLX", "SHM", "SHO", "SHOO", "SHOP", "SHV",
"SHW", "SHY", "SHYF", "SHYG", "SI", "SIBN", "SID", "SIEB", "SIEN", "SIG",
"SIGA", "SIGI", "SIL", "SILJ", "SILK", "SILV", "SIRI", "SITC", "SITE",
"SITM", "SIVB", "SIVR", "SIX", "SJI", "SJM", "SJNK", "SJR", "SJW",
"SKIN", "SKLZ", "SKM", "SKT", "SKX", "SKY", "SKYT", "SKYW", "SKYY",
"SLAB", "SLAM", "SLB", "SLCA", "SLDB", "SLDP", "SLF", "SLG", "SLGC",
"SLGN", "SLI", "SLM", "SLNO", "SLP", "SLQD", "SLQT", "SLRC", "SLV",
"SLVM", "SLVP", "SLY", "SLYG", "SLYV", "SM", "SMAR", "SMB", "SMBC",
"SMBK", "SMCI", "SMCP", "SMDD", "SMDV", "SMDY", "SMED", "SMFG", "SMG",
"SMH", "SMHI", "SMLF", "SMLR", "SMLV", "SMMD", "SMMF", "SMMT", "SMMU",
"SMMV", "SMN", "SMP", "SMPL", "SMR", "SMRT", "SMSI", "SMTC", "SMWB",
"SNA", "SNAP", "SNBR", "SNCR", "SNCY", "SNDL", "SNDR", "SNDX", "SNEX",
"SNFCA", "SNN", "SNOW", "SNPE", "SNPO", "SNPS", "SNSE", "SNSR", "SNTG",
"SNUG", "SNV", "SNX", "SO", "SOFI", "SOI", "SON", "SOND", "SONO", "SOPA",
"SOPH", "SOVO", "SOXL", "SOXS", "SOXX", "SP", "SPAB", "SPB", "SPCE",
"SPDW", "SPEM", "SPFF", "SPFI", "SPG", "SPGI", "SPH", "SPHB", "SPHD",
"SPHQ", "SPIB", "SPIP", "SPLB", "SPLK", "SPLP", "SPLV", "SPMB", "SPMD",
"SPNE", "SPNS", "SPNT", "SPOK", "SPOT", "SPPI", "SPR", "SPRB", "SPRO",
"SPSB", "SPSC", "SPSM", "SPT", "SPTI", "SPTL", "SPTM", "SPTN", "SPTS",
"SPWH", "SPWR", "SPXC", "SPXL", "SPXS", "SPXU", "SPY", "SPYD", "SPYG",
"SPYV", "SQ", "SQFT", "SQL", "SQM", "SQQQ", "SQSP", "SQZ", "SR", "SRC",
"SRCE", "SRCL", "SRDX", "SRE", "SRET", "SREV", "SRG", "SRI", "SRLN",
"SRNE", "SRPT", "SRRK", "SRT", "SRTY", "SRVR", "SSB", "SSBK", "SSD",
"SSL", "SSNC", "SSO", "SSP", "SSRM", "SSTI", "SSTK", "SSYS", "ST",
"STAA", "STAG", "STAR", "STBA", "STC", "STE", "STEL", "STEM", "STEP",
"STER", "STGW", "STIP", "STKL", "STLA", "STLD", "STM", "STNE", "STNG",
"STOK", "STOR", "STPZ", "STR", "STRA", "STRC", "STRL", "STRN", "STRO",
"STRS", "STSA", "STT", "STTK", "STVN", "STWD", "STX", "STXB", "STXS",
"STZ", "SU", "SUB", "SUI", "SUM", "SUMO", "SUN", "SUPN", "SUPV", "SUSA",
"SUSL", "SUZ", "SVC", "SVM", "SVRA", "SVXY", "SWAN", "SWAV", "SWBI",
"SWCH", "SWI", "SWIM", "SWIR", "SWK", "SWKH", "SWKS", "SWM", "SWN",
"SWTX", "SWX", "SXC", "SXI", "SXT", "SYBT", "SYF", "SYK", "SYNA", "SYNH",
"SYRS", "SYTA", "SYY", "SZK", "T", "TA", "TAC", "TACO", "TAIL", "TAL",
"TALO", "TALS", "TAN", "TAP", "TARA", "TARO", "TARS", "TASK", "TAST",
"TBBK", "TBF", "TBI", "TBK", "TBNK", "TBPH", "TBT", "TCBI", "TCBK",
"TCBX", "TCDA", "TCFC", "TCI", "TCMD", "TCOM", "TCRR", "TCRX", "TCS",
"TCX", "TD", "TDC", "TDG", "TDIV", "TDOC", "TDS", "TDSB", "TDSC", "TDTT",
"TDUP", "TDV", "TDW", "TDY", "TEAM", "TECH", "TECK", "TECL", "TECS",
"TEF", "TEL", "TELA", "TELL", "TEN", "TENB", "TER", "TERN", "TETC",
"TEVA", "TEX", "TFC", "TFI", "TFII", "TFIN", "TFSL", "TFX", "TG", "TGB",
"TGH", "TGI", "TGLS", "TGNA", "TGT", "TGTX", "TH", "THC", "THCX", "THD",
"THFF", "THG", "THNQ", "THO", "THR", "THRM", "THRY", "THS", "TIG", "TIGO",
"TIGR", "TIL", "TILE", "TILT", "TIOA", "TIP", "TIPT", "TIPX", "TIRX",
"TISI", "TITN", "TIXT", "TJX", "TK", "TKNO", "TKR", "TLH", "TLIS", "TLK",
"TLMD", "TLRY", "TLS", "TLT", "TLTD", "TLYS", "TMCI", "TMDX", "TME",
"TMF", "TMHC", "TMO", "TMP", "TMST", "TMUS", "TMV", "TMX", "TNA", "TNC",
"TNDM", "TNET", "TNGX", "TNK", "TNL", "TNYA", "TOL", "TOST", "TOTL",
"TOWN", "TPAY", "TPB", "TPC", "TPGY", "TPH", "TPIC", "TPL", "TPR",
"TPTX", "TPX", "TPYP", "TQQQ", "TR", "TRC", "TREC", "TREE", "TREX",
"TRGP", "TRHC", "TRI", "TRIP", "TRKA", "TRMB", "TRMD", "TRMK", "TRN",
"TRNO", "TRNS", "TROW", "TROX", "TRP", "TRQ", "TRS", "TRST", "TRTN",
"TRTX", "TRU", "TRUE", "TRUP", "TRV", "TS", "TSBK", "TSC", "TSCO", "TSE",
"TSEM", "TSHA", "TSLA", "TSLX", "TSN", "TSP", "TSVT", "TT", "TTC",
"TTCF", "TTD", "TTEC", "TTEK", "TTGT", "TTI", "TTM", "TTMI", "TTWO",
"TU", "TUGC", "TUP", "TUR", "TUYA", "TV", "TVTX", "TVTY", "TW", "TWI",
"TWKS", "TWLO", "TWM", "TWNK", "TWO", "TWOA", "TWOU", "TWST", "TWTR",
"TX", "TXG", "TXMD", "TXN", "TXRH", "TXT", "TYL", "TYME", "TZA", "U",
"UA", "UAA", "UAL", "UAN", "UAPR", "UBA", "UBER", "UBFO", "UBP", "UBS",
"UBSI", "UBX", "UCBI", "UCL", "UCO", "UCTT", "UDMY", "UDOW", "UDR",
"UE", "UEC", "UEIC", "UEVM", "UFCS", "UFEB", "UFI", "UFPI", "UFPT",
"UGE", "UGI", "UGP", "UHAL", "UHS", "UHT", "UI", "UIHC", "UIS", "UJAN",
"UJUL", "ULBI", "ULCC", "ULH", "ULST", "ULTA", "UMBF", "UMC", "UMH",
"UMPQ", "UNCY", "UNF", "UNFI", "UNG", "UNH", "UNIT", "UNM", "UNP",
"UNTY", "UNVR", "UOCT", "UP", "UPC", "UPH", "UPLD", "UPRO", "UPS",
"UPST", "UPWK", "URA", "URBN", "URG", "URGN", "URI", "URNM", "URTY",
"USAC", "USB", "USD", "USFD", "USHY", "USIG", "USLM", "USM", "USMC",
"USMV", "USNA", "USO", "USPH", "USRT", "USSG", "USX", "UTF", "UTHR",
"UTI", "UTL", "UTMD", "UTME", "UTZ", "UUP", "UUUU", "UVE", "UVSP", "UVV",
"UVXY", "UWM", "UWMC", "UYG", "V", "VAC", "VACC", "VAL", "VALN", "VALU",
"VAMO", "VAPO", "VAW", "VB", "VBIV", "VBK", "VBR", "VBTX", "VC", "VCEL",
"VCIT", "VCLT", "VCR", "VCSA", "VCSH", "VCTR", "VCYT", "VDC", "VDE",
"VEA", "VEC", "VECO", "VECT", "VEEV", "VEL", "VEON", "VERA", "VERI",
"VERO", "VERU", "VERV", "VERX", "VERY", "VET", "VEU", "VFC", "VFF",
"VFH", "VFQY", "VG", "VGIT", "VGK", "VGLT", "VGR", "VGSH", "VGT", "VHC",
"VHI", "VHT", "VIAO", "VIAV", "VICI", "VICR", "VIDI", "VIG", "VIGI",
"VII", "VINP", "VIOG", "VIOO", "VIOV", "VIPS", "VIR", "VIRI", "VIRT",
"VIS", "VITL", "VIV", "VIVO", "VIXM", "VIXY", "VKTX", "VLD", "VLDR",
"VLGEA", "VLO", "VLON", "VLTA", "VLUE", "VLY", "VMAR", "VMBS", "VMC",
"VMD", "VMEO", "VMI", "VMW", "VNDA", "VNE", "VNLA", "VNO", "VNOM", "VNQ",
"VNQI", "VNRX", "VNT", "VNTR", "VO", "VOD", "VOE", "VONE", "VONG", "VONV",
"VOO", "VOOG", "VOOV", "VOR", "VOT", "VOX", "VOXX", "VOYA", "VPG", "VPL",
"VPOP", "VPU", "VRA", "VRAI", "VRAR", "VRAY", "VRCA", "VRDN", "VRE",
"VREX", "VRM", "VRNS", "VRNT", "VRP", "VRPX", "VRRM", "VRS", "VRSK",
"VRSN", "VRT", "VRTS", "VRTV", "VRTX", "VSAT", "VSCO", "VSEC", "VSGX",
"VSH", "VSS", "VST", "VSTA", "VSTM", "VSTO", "VT", "VTEB", "VTEX",
"VTGN", "VTI", "VTIP", "VTLE", "VTNR", "VTOL", "VTR", "VTRS", "VTRU",
"VTS", "VTV", "VTVT", "VTWO", "VTYX", "VUG", "VUSB", "VUZI", "VV", "VVI",
"VVNT", "VVOS", "VVV", "VVX", "VWO", "VWOB", "VXF", "VXRT", "VXUS", "VXX",
"VXZ", "VYGG", "VYGR", "VYM", "VYMI", "VZ", "VZIO", "W", "WAB", "WABC",
"WAFD", "WAL", "WASH", "WAT", "WAVE", "WB", "WBA", "WBD", "WBIF", "WBIL",
"WBS", "WBT", "WBX", "WCC", "WCLD", "WCN", "WD", "WDAY", "WDC", "WDFC",
"WDH", "WE", "WEBR", "WEC", "WELL", "WEN", "WERN", "WES", "WETF", "WEX",
"WEYS", "WFC", "WFG", "WFH", "WFRD", "WGO", "WH", "WHD", "WHG", "WHR",
"WILC", "WIMI", "WINA", "WING", "WIP", "WIRE", "WISH", "WIT", "WIX",
"WK", "WKHS", "WKME", "WLDN", "WLFC", "WLK", "WLKP", "WLL", "WLY",
"WM", "WMB", "WMC", "WMG", "WMK", "WMS", "WMT", "WNC", "WNEB", "WNS",
"WNW", "WOLF", "WOOF", "WOR", "WOW", "WPC", "WPM", "WPP", "WPRT", "WRB",
"WRBY", "WRE", "WRK", "WRLD", "WSBC", "WSBF", "WSC", "WSFS", "WSM", "WSO",
"WSR", "WST", "WT", "WTBA", "WTFC", "WTI", "WTM", "WTMF", "WTRG", "WTRH",
"WTS", "WTTR", "WTW", "WU", "WUGI", "WVE", "WW", "WWD", "WWE", "WWW",
"WY", "WYNN", "X", "XAIR", "XAR", "XBI", "XBIT", "XCUR", "XEL", "XENE",
"XENT", "XERS", "XES", "XFOR", "XGN", "XHB", "XHE", "XHR", "XITK", "XL",
"XLB", "XLC", "XLE", "XLF", "XLG", "XLI", "XLK", "XLP", "XLRE", "XLU",
"XLV", "XLY", "XM", "XME", "XMLV", "XMTR", "XNCR", "XNTK", "XOM", "XOMA",
"XOP", "XOS", "XP", "XPEL", "XPER", "XPEV", "XPH", "XPO", "XPOF", "XPRO",
"XRAY", "XRT", "XRX", "XSD", "XSLV", "XSOE", "XT", "XTL", "XTN", "XYL",
"YALA", "YANG", "YCS", "YELP", "YETI", "YEXT", "YGMZ", "YINN", "YLD",
"YMAB", "YMM", "YOLO", "YORW", "YOU", "YPF", "YQ", "YSG", "YTRA", "YUM",
"YUMC", "YY", "YYY", "Z", "ZBH", "ZBRA", "ZCMD", "ZD", "ZEN", "ZENV",
"ZETA", "ZEUS", "ZG", "ZGN", "ZGNX", "ZH", "ZI", "ZIM", "ZIMV", "ZION",
"ZIP", "ZLAB", "ZM", "ZME", "ZNGA", "ZNTL", "ZOM", "ZROZ", "ZS", "ZSL",
"ZTO", "ZTS", "ZUMZ", "ZUO", "ZVIA", "ZWS", "ZYME", "ZYXI"]

# Create an empty dictionary to store data
#historical_data = {}

today = datetime.today().strftime("%Y%m%d")

basedir = f"/home/xdli/database_py/yahoo/{today}"
os.makedirs(basedir, exist_ok=True )


def get_info(symbol, basedir):
    print(f"Fetching reference data for {symbol} to {basedir}...")
    stock = yf.Ticker(symbol)
    info = stock.info
    info_df = pd.DataFrame(info.items(), columns=['Key', 'Value'])
    info_df.to_csv( f"{basedir}/stockinfo/{symbol}.csv", index=False)

def get_pricevolume(symbol, basedir):
    print(f"Downloading {symbol} to {basedir}...")
    today2 = datetime.today().strftime("%Y-%m-%d")
    data = yf.download(symbol, start="2010-01-01", end=today2)  # Adjust dates as needed
    data.to_csv( f"{basedir}/pricevolume/{symbol}.csv")

# Download historical data for each symbol
for symbol in symbols:
    #get_pricevolume(symbol, basedir, date2)
    get_info(symbol, basedir)
